# Generated by Django 5.2.1 on 2025-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('GB', 'United Kingdom'), ('AU', 'Australia'), ('CA', 'Canada')], default='IN', max_length=2),
        ),
    ]
